from __future__ import annotations

from decimal import Decimal
from typing import Annotated, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    FiniteFloat,
    field_validator,
    model_validator,
)


ShortText = Annotated[str, Field(max_length=500)]
LongText = Annotated[str, Field(max_length=12_000)]
Money = Annotated[FiniteFloat, Field(ge=0)]
DocumentType = Literal[
    "PO",
    "PR",
    "HOADON",
    "BBBG",
    "BAOGIA",
    "HOPDONG",
    "UNC",
    "PHIEUTHU",
    "KHAC",
]
RuleStatus = Literal["dat", "loi", "xem"]
RuleId = Literal[
    "A1",
    "A2",
    "A3",
    "A4",
    "A5",
    "B1",
    "B2",
    "B3",
    "C1",
    "D1",
    "X1",
    "X2",
    "X3",
    "X4",
    "K1",
]


class StrictModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        strict=True,
        str_strip_whitespace=True,
    )


class CheckInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    eform: Annotated[str, Field(min_length=1, max_length=200)]
    type: Literal["PO/PR"]
    is_inv: bool = False
    item_number: Annotated[str, Field(max_length=200)] = ""
    payee: Literal["NV", "NCC"] = "NCC"

    @model_validator(mode="after")
    def require_item_for_inventory_po(self) -> "CheckInput":
        if self.is_inv and not self.item_number:
            raise ValueError("item_number is required for inventory PO")
        if not self.is_inv:
            self.item_number = ""
        return self


class Summary(StrictModel):
    ncc: ShortText
    mst: ShortText
    so_po: ShortText
    so_pr: ShortText
    budget_code: ShortText
    product_code: Annotated[str, Field(pattern=r"^\d{3}$")]
    loai_hang: Literal["thiet_bi", "dich_vu", "khac"]
    mo_ta_hang: LongText
    so_luong: LongText
    don_gia_truoc_thue: Money
    truoc_vat: Money
    vat: Money
    tong: Money
    tru_ns_pr: Money
    ngay_hoa_don: ShortText
    ngay_bbbg: ShortText
    hinh_thuc_tt: ShortText
    term_thanh_toan: LongText
    tk_nhan_tren_unc: ShortText

    @model_validator(mode="after")
    def validate_invoice_total(self) -> "Summary":
        before_vat = Decimal(str(self.truoc_vat))
        vat = Decimal(str(self.vat))
        total = Decimal(str(self.tong))

        # The model uses zero when a monetary field cannot be extracted. Only
        # enforce the identity when at least two values carry information; all
        # zeroes and a lone known value remain reviewable rather than rejected.
        known_values = sum(value != 0 for value in (before_vat, vat, total))
        if known_values >= 2 and abs((before_vat + vat) - total) > Decimal("1"):
            raise ValueError("truoc_vat + vat must equal tong within 1 VND")
        return self


class RuleResult(StrictModel):
    id: RuleId
    ten: Annotated[str, Field(min_length=1, max_length=500)]
    trang_thai: RuleStatus
    chi_tiet: LongText

    @field_validator("id", mode="before")
    @classmethod
    def normalize_rule_id(cls, value: object) -> object:
        return value.strip().upper() if isinstance(value, str) else value


class DocumentResult(StrictModel):
    ten_file: Annotated[str, Field(min_length=1, max_length=500)]
    loai: DocumentType
    fields: dict[ShortText, LongText]
    rules: list[RuleResult]


class ReviewResult(StrictModel):
    tong_hop: Summary
    docs: list[DocumentResult]

    @model_validator(mode="after")
    def reject_duplicate_business_rules(self) -> "ReviewResult":
        seen: set[str] = set()
        for document in self.docs:
            for rule in document.rules:
                # K1 is a per-file fallback generated by the backend, so it may
                # legitimately appear on multiple unclassified documents.
                if rule.id == "K1":
                    continue
                if rule.id in seen:
                    raise ValueError(f"duplicate business rule: {rule.id}")
                seen.add(rule.id)
        return self


# Internal structured schemas used by the chunk/map/reduce pipeline.
class EvidenceValue(StrictModel):
    nhan: ShortText
    gia_tri: LongText
    nguon_file: ShortText
    vi_tri: ShortText


class RuleSignal(StrictModel):
    rule_id: RuleId
    trang_thai_goi_y: Literal["dat", "loi", "xem", "chua_du_thong_tin"]
    chi_tiet: LongText
    nguon_file: ShortText
    vi_tri: ShortText

    @field_validator("rule_id", mode="before")
    @classmethod
    def normalize_rule_id(cls, value: object) -> object:
        return value.strip().upper() if isinstance(value, str) else value


class EvidenceDocument(StrictModel):
    ten_file: ShortText
    loai_goi_y: DocumentType
    du_lieu: list[EvidenceValue]
    dau_hieu_rule: list[RuleSignal]
    thong_tin_khac: list[LongText]
    diem_khong_chac_chan: list[LongText]


class EvidencePacket(StrictModel):
    tai_lieu: list[EvidenceDocument]
    doi_chieu_cheo: list[LongText]
    mau_thuan: list[LongText]


class MapResult(StrictModel):
    source_id: Annotated[str, Field(min_length=1, max_length=80)]
    evidence: EvidencePacket


class ReduceResult(StrictModel):
    evidence: EvidencePacket
